//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ApplicationID { get; set; }
        public int UserID { get; set; }
        public int FormID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int Status { get; set; }
        public string FullName { get; set; }
        public string Reasons { get; set; }
    }
}
