//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SemesterDropApplicationRecord
    {
        public int Application_ID { get; set; }
        public bool SemesterOne { get; set; }
        public bool SemesterTwo { get; set; }
        public bool SemesterThree { get; set; }
        public bool SemesterFour { get; set; }
        public bool SemesterFive { get; set; }
        public bool SemesterSix { get; set; }
        public bool SemesterSeven { get; set; }
        public bool SemesterEight { get; set; }
    }
}
