//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workflow
    {
        public int WFID { get; set; }
        public int AppliationID { get; set; }
        public int ApproverID { get; set; }
        public int Status { get; set; }
        public System.DateTime Time { get; set; }
        public int Order { get; set; }
        public string Remarks { get; set; }
    }
}
